library('dplyr')  
library('ggplot2')   
library('raster') 
library('terra')
library('sf')
library('tidyr')

#import data -----------------------------------------------------------------------------------------------

cutblocks <- st_read('Tweedsmuir/Harvested_cuts_sa_WGS/harvested_cuts_sa_WGS.shp') #shapefile for cutblock areas in Tweedsmuir

tweeds.files <-
  list.files(path = 'Tweedsmuir/NDVI/VI_16Days_250m_v61/NDVI/',
             pattern = '.tif', full.names = TRUE) #NDVI data

#data wrangling ----------------------------------------------------------------------------------------------

#combine cutblock spatial information with tweedsmuir ndvi data
data <- list()

for(i in 1:length(tweeds.files)){

  tweeds.raster <- terra::rast(tweeds.files[i]) # rasterize each file
  
  cb <- list()
  
  for (j in 1:nrow(cutblocks)){
    
    #create data frame with combined data
     cb.dat <- 
      terra::crop(tweeds.raster, cutblocks[j,], snap = "out") %>%
      as.data.frame(xy = TRUE) %>%
      na.omit()
     
     #create a logical column to indicate data is located within a cutblock
    names(cb.dat)[3] <- "NDVI"
    if(nrow(cb.dat) > 0){
    cb.dat$cutblock <- TRUE
    cb.dat$harvestyr <-  cutblocks[j,]$HARVESTYR
    }
    cb[[j]] <- cb.dat
    
  }

  cb <- do.call(rbind, cb)
  d.all <- as.data.frame(tweeds.raster, xy = TRUE)
  
  #merge all data into a dataframe with ndvi outside cutblocks
  d.all <-  merge(x = d.all,
                  y = cb,
                  by.x = c("x","y"),
                  by.y = c("x","y"),
                  all.x = T)
  d.all$NDVI <- NULL
  names(d.all)[3] <- "NDVI"
  d.all[is.na(d.all$cutblock),"cutblock"] <- FALSE
  d.all$date <- as.Date(substr(names(tweeds.raster),
                               start = nchar('MOD13Q1_NDVI_x'),
                               stop = nchar(names(tweeds.raster))),
                        format = '%Y_%j')
  
  data[[i]] <- d.all
  
  #Save the resulting dataframe
  saveRDS(d.all, paste0("Tweedsmuir/Data/",paste(names(tweeds.raster),"_Annotated.rds", sep = ""))) #save the dataframe
  rm(d.all); rm(cb) #clean environment
  print(i) #indicate when each layer has been completed
  
}

DATA <- do.call(rbind, data)

#data carpentry---------------------------------------------------------------------------------------

#load in all the files generated by previous step
rdsfiles <- list.files(path = 'Tweedsmuir/Data/',
             pattern = '.rds', full.names = TRUE)

d <- list()
for(i in 1:length(rdsfiles)){
  r <- readRDS(rdsfiles[i])
  d[[i]] <- r
}

#this step takes a long time
data <- do.call(rbind, d)

as.data.frame(data)

#add in necessary variables for analysis
d <- mutate(data,
            dec_date = decimal_date(date),
            year = year(date),
            doy = yday(date),
            cb_age = (year - harvestyr))

names(d)[names(d) == 'x'] <- 'long'
names(d)[names(d) == 'y'] <- 'lat'

#convert data to formats that take less space
d$year <- as.integer(d$year) 
d$doy <- as.integer(d$doy)
d$cb_age <- as.integer(d$cb_age)
d$cutblock <- as.factor(d$cutblock)

#replace negatives and NAs with o
d["harvestyr"] [is.na(d["harvestyr"])] <- 0
d["cb_age"] [is.na(d["cb_age"])] <- 0
d["cb_age"] [d["cb_age"] < 0] <- 0 

saveRDS(d, 'Tweedsmuir/data.rds') #save resulting data

